### ISSUE TITLE
Agenda: Group Check-In with Evan

### ISSUE THREAD

**Issue by MaabTaha** [MIT-Emerging-Talent/2024-group-03-cdsp#1]
### Milestone 1: Problem Identification
- [ ] Research question
  - Does it have to be something unique and new?
  - Would starting with specifying a target group be a good start after deciding the domain?
- [ ] Constraints 
  - Is age range for the people we want to focus on considered a constraint?
- [ ] Scope
   - Need further explanation
- [ ] Engagement - do you want to merge with anther group? (evan)

**Comment by colevandersWands** [comment]
A partial answer here before we meet tomorrow: Scope is which objectives you will and will not include in the project, scope is heavily influenced by your project constraints but they are not the same thing.  

I would consider target groups and age range to be part of your project's scope, the demographic you want to study is related to your objectives.  Constraints are more about your group's capacity and limitations, which _constrain_ which objectives you can realistically achieve.
