### ISSUE TITLE
Final presentation

### ISSUE THREAD

**Issue by pavlo-iakymenko** [MIT-Emerging-Talent/2024-group-03-cdsp#24]
1. Collect all ideas about final presentation https://docs.google.com/document/d/126p3okFA0Qf0yrCqL6xm-_qOf1SXl0qWBMl-4Yv7d7c/edit
2. attend Pitch & Communication Skills - CDSP Workshop 
3. Compose final presentation

**Comment by tvsirius** [comment]
add summation of one of our main ideas about changes we are heading to contribute

**Comment by pavlo-iakymenko** [comment]
1. A 1-minute pitch for your solution.
2. A 3-minute presentation of your
group’s process from beginning to end
including challenges you faced,
lessons you learned, and any advice
you have for future learners.

**Comment by tvsirius** [comment]
Gentle reminder of what we have for this week:
We have issued tasks needs to be done - issues in our project repository. Please choose not assigned tasks and contribute
Deliverables for this week:
We have started to work on describing our audience and writing our story plan is this doc
https://docs.google.com/document/d/126p3okFA0Qf0yrCqL6xm-_qOf1SXl0qWBMl-4Yv7d7c/edit
Everyone is welcome to contribute

**Comment by Wagoory** [comment]
DONE!!
