### ISSUE TITLE
Write Retrospectives for Milestones 2 and 4

### ISSUE THREAD

**Issue by Yulia-Sych** [MIT-Emerging-Talent/2024-group-03-cdsp#29]
Write retrospective files and move Retrospective 3 to Collaboration/Retrospective folder. Delete second Retrospective folder.

**Comment by Yulia-Sych** [comment]
Folders've already been reorganized.

**Comment by pavlo-iakymenko** [comment]
added template for both docs

**Comment by pavlo-iakymenko** [comment]
we will meet / collaborate for retro 4, correct?
