### ISSUE TITLE
Create README for the Data Collection folder

### ISSUE THREAD

**Issue by Yulia-Sych** [MIT-Emerging-Talent/2024-group-03-cdsp#30]
A non-technical explanation of how you chose to model your domain, and possible flaws in this approach, in your README. (visuals can be very helpful!)

**Comment by tvsirius** [comment]
https://docs.google.com/document/d/1nzOBzuTgNCnghBkFcH8mq7668mJNukuaXoMGSnNw0Zs/edit#heading=h.6j05eaioxy24

**Comment by Yulia-Sych** [comment]
Add the link on google drive document with datasets

**Comment by pavlo-iakymenko** [comment]
added some layout and links
