### ISSUE TITLE
Target Audience Description (part of Milestone 4: Communicating Results)

### ISSUE THREAD

**Issue by Yulia-Sych** [MIT-Emerging-Talent/2024-group-03-cdsp#32]
A document describing your target audience, their capabilities and constraints, how you intend to reach them, what you would like them to learn, and how you hope they will act.
(Personas can be helpful!)

**Comment by tvsirius** [comment]
this is the document, for now
https://docs.google.com/document/d/126p3okFA0Qf0yrCqL6xm-_qOf1SXl0qWBMl-4Yv7d7c/edit
