### ISSUE TITLE
Add Personas to Personas.md (Milestone 4: Communicating Results)

### ISSUE THREAD

**Issue by MaabTaha** [MIT-Emerging-Talent/2024-group-03-cdsp#35]
Create a couple of personas (specific examples of people) of the people we are targeting, here are three examples provided in one of the sessions (link to slides https://docs.google.com/presentation/d/1EN1xYW9DVDjkz0RNuJzEUePt2sKzKny5VxmeR1uceto/edit?usp=sharing ):

Françoise Lefèvre (f, 54)

Background: She is a 1st generation Belgian born to a french-speaking family from Switzerland. She studied accounting and worked for the Brussels government for 23 years.

Entered Politics Because: She was tired of politicians not understanding city finances, she believed her experience as a government accountant would benefit residents of Brussels.

Speaks: French, English, Swiss German

Fara Alami (f, 39)
Background: She is a 3rd generation Belgian born to a French & Arabic speaking family with roots in Morocco. She studied chemistry and worked as a researcher in a local university for 10 years where she was also the faculty representative on the university's board.
Entered Politics Because: She enjoyed her work more as a board member than as a researcher and wanted to be part of decision-making for a larger community.
Speaks: French, Arabic, Dutch, English

Koen Van Dyck (m, 42)

Background: He was born to a dutch-speaking family that has lived in Brussels since Belgium was formed. He studied web design and worked as an independent developer for 15 years, most of his clients were small businesses or nonprofits.

Entered politics because: His experience working with nonprofits gave him many ideas of how local government can better support social initiatives.

Speaks: English, French, Dutch

**Comment by polly-wolly** [comment]
added into the google doc file 2 additional personas 
https://docs.google.com/document/d/126p3okFA0Qf0yrCqL6xm-_qOf1SXl0qWBMl-4Yv7d7c/edit?usp=sharing

**Comment by tvsirius** [comment]
Good information about our audience

**Comment by tvsirius** [comment]
This issue is done
