### ISSUE TITLE
Milestone 2: Data Collection and Datasets

### ISSUE THREAD

**Issue by MaabTaha** [MIT-Emerging-Talent/2024-group-03-cdsp#4]
We initially decided to explore the relation between the use of AI and mental health, this idea is very broad and we haven't narrowed it down so we are kind of all over the place. 
This meeting isn't a group meeting, I scheduled it because I feel lost about datasets (I've invited my teammates to join if they would like and some requested a recording of the meeting). I would like to know more about what can be considered as data that we can use. A question I have is whether we can use articles and research papers, and gather the information/conclusions they've reached as data. We might not be able to gather lots of data of this type. 
I would also like to go through an example of a dataset and what happens after finding a dataset because this is not clear to me. Maybe we can go through one of the stories from our domain and data session, and go through one of the datasets of the stories and how they've used it to reach their conclusion.

**Comment by colevandersWands** [comment]
Hi @MaabTaha, a quick half-answer before our call today.  Text is data!  If the best data you can find for your questions are research papers, then NLP could be a good analysis strategy moving forward.   I know I've cautioned against NLP in the workshops - my concern was that groups would run towards NLP as a solution before looking more broadly for other data sources.  

> I would also like to go through an example of a dataset and what happens after finding a dataset because this is not clear to me.

Don't worry about this just yet!  We'll cover this in our workshop on Monday
